ansible_connection: network_cli
ansible_network_os: cisco.ios.ios

ansible_user: admin
ansible_password: "{{ vault_ios_password }}"

# je≈õli potrzebne enable:
ansible_become: true
ansible_become_method: enable
ansible_become_password: "{{ vault_ios_enable_password }}"
