---
- name: Simple SSH connection test
  hosts: all
  gather_facts: no

  tasks:
    - name: Run "show version"
      ansible.netcommon.cli_command:
        command: show version
      register: result

    - name: Display output
      debug:
        var: result.stdout_lines
