---
- name: Cisco IOS sanity check
  hosts: sw1
  gather_facts: no
  tasks:
    - name: Show clock (sanity test)
      cisco.ios.ios_command:
        commands:
          - show clock
      register: out

    - name: Print output
      ansible.builtin.debug:
        var: out.stdout_lines
